bridge:
  # Port to host the bridge on which your homeserver will connect to
  port: 6000
  # Address for the bridge to bind to; if running as a Docker container, you
  # probably want 0.0.0.0 here
  bindAddress: localhost
  # Name of your homeserver
  domain: matrix.example.com
  # URL where the bridge can connect to your homeserver
  homeserverUrl: http://matrix.example.com:8008

provisioning:
  # Which users are allowed to issue commands to @_toxpuppet_bot
  # whitelist:
  #  - "@*:matrix.example.com"
  # A blacklist can be used instead:
  # blacklist:
  #   - "@username:matrix\\.myhomeserver\\.com"

  # Shared secret for the provisioning API for use by integration managers.
  # If this is not set, the provisioning API will not be enabled.
  #sharedSecret: random string
  # Path prefix for the provisioning API. /v1 will be appended to the prefix automatically.
  apiPrefix: /_matrix/provision

presence:
  # Bridge Tox online/offline status
  enabled: true

  # How often to send status to the homeserver in milliseconds
  interval: 5000
